### ISSUE TITLE
something is not right with documentation

### ISSUE THREAD

**Issue by aaronksaunders** [kamilkisiela/loona#104]
This looks , interesting... having challenges following along with instructions and then the examples are drastically different than the provided instructions.

So I basically cut and pasted the code from your directions and it is throwing errors...

<img width="825" alt="screen shot 2018-09-22 at 9 36 57 pm" src="https://user-images.githubusercontent.com/524953/45923270-ba5cd380-beaf-11e8-969b-8cbc59664cdf.png">

I also noticed the instructions don't specifically tell you to set the vlaue of the store in the `app.module.ts`

first import the `State`
```
import State from './app-state'
```
Then set it on the Loona module

```
imports: [BrowserModule, FormsModule, ApolloModule, LoonaModule.forRoot([State])],
```

The source code is here on stackblitz 

https://stackblitz.com/edit/angular-esypth

**Comment by aaronksaunders** [comment]
i eventually got it all to work, but there needs to be some edits made to the documentation : https://stackblitz.com/edit/angular-loona-sample 👍

**Comment by kamilkisiela** [comment]
Thank you, I'm going to check it soon. Documentation is still a work in progress

**Comment by aaronksaunders** [comment]
Well until the documentation is correct can I suggest that you at a minimum have the complete source code for the project in the documentation available so some one has a basic starting point that works?

**Comment by kamilkisiela** [comment]
O guess I'll base the documentation on an example as you propose so it'll be a documentation/tutorial
